import React from 'react'

function  Sidebar() {
  return (
    <div className='h-[100vh] overflow-y-scroll scroll-hidden'>
        <p className="mt-2 text-gray-600">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dictum urna non aliquet ultrices. Cras a lacus malesuada, pretium est semper, viverra lacus. Aenean ultrices feugiat malesuada. Fusce cursus placerat libero, sed tincidunt tortor scelerisque eget. Quisque consequat velit ac massa vulputate efficitur. Nulla laoreet lectus in nulla interdum, non scelerisque libero hendrerit. Duis fermentum sed ante eget mollis. Integer feugiat lacus nec leo blandit, ut lacinia ante convallis. Nullam tincidunt pellentesque nunc rhoncus vestibulum. Phasellus mollis maximus turpis, ut laoreet urna scelerisque quis. Phasellus elementum rhoncus porttitor. Pellentesque dolor augue, sodales eget vestibulum non, lacinia porta ante.

Phasellus eu porttitor est. Maecenas suscipit bibendum nisl id ornare. Nunc euismod fermentum lorem nec semper. Nam commodo, ante vitae laoreet auctor, mi urna faucibus metus, id fermentum nibh eros ornare nibh. Duis eu accumsan lectus. Quisque at egestas velit, eget mattis mi. Sed ut hendrerit ligula. Integer faucibus in tortor in hendrerit. Aenean gravida pharetra erat. Vestibulum pharetra porttitor posuere. Donec at tempus arcu. Curabitur euismod diam non ultrices scelerisque. Phasellus pellentesque laoreet ante ac accumsan. In at dapibus turpis. Nullam auctor metus ultrices quam dignissim, at molestie lorem porta.

Donec blandit dui vitae sem varius tempus. Suspendisse potenti. Integer at venenatis eros. Vivamus at turpis in turpis eleifend maximus sed sit amet enim. Aenean ac odio a ante euismod pulvinar. Etiam ac efficitur augue. Cras ex arcu, laoreet vehicula imperdiet vel, sollicitudin sed lacus. Integer rutrum scelerisque arcu sit amet commodo. Praesent fringilla felis sed dignissim fringilla. Praesent at lacinia metus.

Integer ullamcorper pulvinar lectus, sed varius velit vestibulum efficitur. Donec mi elit, vestibulum ut diam eu, luctus iaculis arcu. Nulla facilisi. Praesent eget ligula maximus, pretium tellus convallis, lobortis nibh. Sed nec lectus sit amet purus elementum pretium pellentesque nec tortor. Donec vitae nibh tortor. Praesent lorem massa, imperdiet eget ligula in, fermentum tincidunt ex. Nunc ante nisi, maximus id faucibus id, luctus et dolor. Sed justo risus, auctor eget dictum at, aliquam sed erat. Curabitur dapibus faucibus nisi nec sollicitudin. Sed vestibulum justo ex, ut maximus sem efficitur eget. Sed eleifend purus quis ultrices mattis. Etiam non purus tincidunt, eleifend mauris congue, hendrerit ipsum. Nam sit amet orci ut nisl fringilla varius sed nec risus. Mauris varius justo in dui laoreet, ut suscipit augue semper.

Phasellus non gravida sapien. Ut blandit quam a turpis consequat, nec vestibulum dui cursus. Quisque interdum elementum quam nec fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris a sapien at enim fringilla lobortis. Pellentesque cursus lacus vel elit ornare, sit amet faucibus libero efficitur. Integer porta, turpis vel posuere tristique, justo risus placerat est, eget porttitor urna lorem ac velit. Duis ac est rutrum, semper nibh eu, ullamcorper est. Ut pellentesque ut diam in rhoncus. Praesent dignissim non elit sit amet congue. Phasellus suscipit nisl id erat facilisis porttitor. Maecenas velit lectus, mattis condimentum volutpat in, convallis eu urna. Maecenas consectetur egestas magna eget molestie. Nam vitae diam sollicitudin, maximus quam eget, tempor erat.

Pellentesque sit amet hendrerit lorem. Nam sit amet sapien nisi. Curabitur egestas ligula non velit porta egestas. Etiam ullamcorper non ex ut egestas. Phasellus interdum massa sed neque mollis, vitae molestie sem iaculis. Nullam mauris justo, fringilla nec dignissim ut, ultrices sed diam. Donec finibus, nibh sed commodo euismod, libero tortor malesuada lacus, ac pharetra dui lectus sit amet enim. Vivamus nec leo a felis congue elementum eget convallis neque. Donec consequat fringilla feugiat. Etiam diam enim, malesuada condimentum lectus sit amet, facilisis hendrerit nibh.

Nullam bibendum tellus sed convallis aliquet. Vestibulum pulvinar elit at viverra efficitur. Sed lobortis justo id porta elementum. Quisque dictum eu purus vitae laoreet. Nunc egestas arcu vel iaculis malesuada. In cursus commodo sapien, nec tincidunt risus gravida vel. Pellentesque arcu leo, fringilla ac ligula eget, sagittis efficitur lacus. Donec et rutrum justo. Nam elit tellus, pretium non nunc a, eleifend iaculis velit. Sed ac nisi mattis, dictum diam sed, bibendum dui. Nullam laoreet, risus eu sollicitudin egestas, dolor metus lobortis nisi, non pharetra tellus turpis id odio. Fusce pretium a ligula non molestie. In non ullamcorper elit. Nulla tempor orci vitae velit hendrerit, sed ornare massa rutrum. Duis auctor placerat est at lobortis. Nullam efficitur ex eget libero sollicitudin, quis fringilla enim faucibus.

Nam et leo turpis. Sed commodo pulvinar mattis. Nulla ullamcorper mi tortor, ac rutrum ante semper sit amet. Maecenas pellentesque diam vitae neque faucibus rutrum. Nullam sollicitudin convallis consequat. Aliquam sem massa, gravida id vulputate sed, blandit condimentum leo. Nullam pretium, nisi non vestibulum maximus, lorem risus tristique ipsum, eget varius lectus ipsum vel nisi. Ut elementum enim est, sit amet interdum leo vulputate at. Praesent suscipit eleifend dolor, at pulvinar lorem bibendum eget. Vivamus vitae urna id eros cursus euismod vitae et justo. Aenean sit amet elementum enim.

Vivamus diam justo, tristique a velit pharetra, varius lobortis nibh. Nam ornare feugiat malesuada. Sed id lectus nunc. Morbi a tincidunt risus, quis facilisis nulla. Vestibulum at ipsum et lectus mollis tincidunt. Fusce imperdiet lobortis felis eget sodales. Aenean tempor vehicula velit. Suspendisse consectetur eros eleifend velit scelerisque, gravida facilisis diam fringilla. Nullam volutpat nibh non eros tincidunt volutpat. Phasellus quis ex orci. Nunc viverra ultricies mauris eget vestibulum. Suspendisse turpis est, tristique sit amet euismod sed, congue eget lectus. Nam aliquet diam sit amet tempor rhoncus. Sed in volutpat dolor.

Donec egestas laoreet tempor. Phasellus velit ex, tincidunt at lobortis a, egestas lacinia eros. Suspendisse id est eget nulla fringilla iaculis. Cras nec elit aliquet, porta diam ut, tincidunt massa. Pellentesque quis efficitur elit. Curabitur semper, dolor eu malesuada faucibus, nulla nunc vulputate velit, eu elementum ex ipsum vel sapien. Etiam in ex quis neque cursus viverra eget in est. Proin id fringilla ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vitae risus quis mi viverra tempor. Nullam ac fringilla ligula, a vehicula felis. Nunc interdum dui gravida nisl mattis varius. Fusce nisi dolor, sodales vel mauris sodales, pharetra sodales dolor. Pellentesque eleifend at ligula eget posuere. Aenean accumsan nisl sapien, id rutrum felis fringilla a. Quisque laoreet eros id congue varius. Nam pretium, quam sed convallis aliquam, purus tellus egestas erat, nec sagittis ipsum ante nec nulla.

Nulla facilisi. Nulla fringilla a ex vel blandit. Vestibulum efficitur tellus eget sem vestibulum, nec pharetra odio pretium. Fusce porta facilisis tincidunt. Aliquam commodo felis eu ipsum imperdiet tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eget eros dui. Aenean faucibus risus porttitor diam molestie lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam convallis nulla pulvinar sem convallis lacinia.

Nam vestibulum nec lectus quis bibendum. In sit amet ex quis erat egestas viverra vel vel justo. Donec turpis nisi, volutpat vel elit vitae, elementum vestibulum augue. Pellentesque rhoncus ex mi, id finibus lorem tristique ac. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin nec lorem lacinia, pellentesque tellus sit amet, mollis ipsum. Maecenas gravida lobortis leo, id vulputate eros condimentum rhoncus.

Sed vel gravida diam. Vivamus id venenatis purus. Proin ut eleifend ex. Ut elit dui, fermentum ut arcu ut, consectetur aliquet mi. Donec nulla elit, suscipit congue commodo ac, volutpat eu ipsum. Maecenas vitae rhoncus lectus, nec tempor dolor. Maecenas velit mauris, tincidunt nec tincidunt nec, tristique eu risus. Aenean vitae odio elit. Nunc blandit dui vitae sem elementum, a efficitur justo commodo. Curabitur sollicitudin molestie leo et maximus.

Vivamus rutrum augue in lacinia sagittis. Aenean posuere massa neque, id rutrum eros mattis vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis at augue sit amet ultricies. Duis at mauris in est ultricies accumsan sit amet a nibh. Aenean id purus at dolor mattis laoreet at sit amet odio. Donec metus urna, blandit ut nibh nec, interdum tristique leo. Donec pulvinar pretium sagittis. Vestibulum eu metus at quam aliquet aliquam nec a urna. Sed sollicitudin felis ut ante luctus, ut feugiat sem interdum. Donec ut imperdiet ligula. Curabitur tincidunt porttitor sodales.

Fusce euismod lorem ut tempus auctor. Proin id erat eu augue interdum aliquet. Suspendisse sed magna nec augue viverra lacinia nec et mauris. Sed a mollis ante. Nunc ut nulla elementum, vehicula massa vel, fringilla massa. Nam dictum, nulla eget sodales gravida, erat dui venenatis libero, ac semper massa lacus in velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed fermentum quam augue, vel ornare libero semper vitae.

Etiam sit amet augue et tellus euismod tincidunt. Phasellus libero sem, aliquam sed nibh sit amet, mollis tempor mi. Nam luctus pulvinar ligula. In ultricies arcu ut erat euismod iaculis. Morbi eu ultricies turpis. Nam pretium, magna sed congue eleifend, eros velit mattis eros, at tempor dolor augue id arcu. Aliquam aliquet ornare nunc facilisis dapibus. Curabitur at iaculis metus. Ut consectetur ullamcorper lacus eget accumsan. Fusce fringilla sapien nec diam ornare, vel tempus ligula tempor. Vivamus efficitur accumsan tincidunt. Aliquam vel lobortis lacus, ut ullamcorper arcu.

Donec suscipit libero nec gravida tempor. Mauris non mattis nisl, id molestie sapien. Sed porttitor neque at lobortis ullamcorper. Maecenas sed aliquet mi, nec bibendum lorem. Etiam ac scelerisque tellus, vitae consequat nisi. Donec purus nisi, varius a urna id, fermentum lobortis dui. Curabitur imperdiet metus eget diam sollicitudin viverra.

Nunc a tristique nisi. Sed mattis, tortor non auctor suscipit, lectus velit luctus massa, sed ultrices mi nisl tempus ante. Etiam hendrerit magna neque, eget ornare leo lobortis sit amet. Fusce in tellus vehicula, rutrum dui id, pellentesque ex. Maecenas mi velit, hendrerit eget nisi vitae, pellentesque faucibus mi. Sed molestie semper nunc in commodo. Vestibulum sit amet mattis urna. Maecenas dapibus mi sed mauris ultrices dapibus. Aenean efficitur fringilla justo. Maecenas auctor lorem venenatis tellus vestibulum, eget ultricies nibh finibus. Aliquam eu condimentum mi. Mauris id ullamcorper risus, sed suscipit nunc. Nullam odio mauris, interdum quis dictum placerat, eleifend a lacus. Nam sollicitudin ipsum mollis risus semper, vitae dapibus quam bibendum.</p>
    </div>
  )
}

export default  Sidebar